- name: deploy chatapp
  hosts: 
    - prod_azure
  gather_facts: yes
  remote_user: ayedhaithem1
  vars:
      NODEJS_VERSION: "10"
      ansible_distribution_release: "xenial" #trusty
  #become: yes
  become_user: ayedhaithem1
  tasks:
      - name : "git clone"
        git:
          repo: https://github.com/AyedHaithem1/chatapp.git
          dest: /home/ayedhaithem1/chatapp
          version: master
          force: yes
      
      - name: "Installing dependecy for back-end"
        npm :
          path: /home/ayedhaithem1/chatapp/backend
      
      - name: "Installing dependecy for front-end"
        npm :
          path: /home/ayedhaithem1/chatapp/react-app
