- name: deploy chatapp
  hosts: 
    - prod_azure
  gather_facts: yes
  remote_user: tnadmin
  vars:
      NODEJS_VERSION: "10"
      ansible_distribution_release: "xenial" #trusty
  become: yes
  #become_user: tnadmin
  tasks:
      - name: Install git
        apt:
          name: git
          state: present
          update_cache: yes

      - name: install lighttpd
        apt:
          name: lighttpd
          state: present

      - name: "Install forever (to run Node.js app)."
        npm: name=forever global=yes state=present

      - name: "Install http-server."
        npm: name=http-server global=yes state=present

      - name: "Check list of Node.js apps running."
        command: forever list
        register: forever_list
        changed_when: false

      - name : "git clone"
        git:
          repo: https://github.com/AyedHaithem1/chatapp.git
          dest: /home/tnadmin/chatapp
          version: master
          force: yes
      
      - name: "Installing dependecy for back-end"
        npm :
          path: /home/tnadmin/chatapp/backend
      
      - name: "Installing dependecy for front-end"
        npm :
          path: /home/tnadmin/chatapp/react-app
      
      - name: "Start backend."
        command: forever start /home/tnadmin/chatapp/backend/server.js
        when: "forever_list.stdout.find('/home/tnadmin/chatapp/backend/server.js') == -1"

      - name: build front
        shell:
          cmd: npm run-script build
          chdir: /home/tnadmin/chatapp/react-app

      - name: start front
        shell: lighttpd -f /home/tnadmin/chatapp/react-app/lighttpd.conf
