- name : deploy chatapp
    hosts: all
    gather_facts: yes
    remote_user: ayedhaithem1
    vars:
        NODEJS_VERSION: "10"
        ansible_distribution_release: "xenial" #trusty
    tasks:
        - name: Install the gpg key for nodejs LTS
          apt_key:
            url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
            state: present

        - name: Install the nodejs LTS repos
          apt_repository:
            repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
            state: present
            update_cache: yes

        - name: Install the nodejs
          apt:
            name: nodejs
            state: present
        
        - name : "git clone"
          git:
            repo: https://github.com/AyedHaithem1/chatapp.git
            dest: /opt/chatapp
            version: master
            force: yes
        
        - name: "npm install"
          npm :
            path: /opt/chatapp/backend
        
        - name: "npm install"
          npm :
            path: /opt/chatapp/react-app
        
        